# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ccdaa6d0f35a3bd7fee1297a696cc660"
application_url = "https://example.com"
embedded = true
name = "Translation Coverage Audit"

[access_scopes]
scopes = "read_products,read_translations"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
